@extends('layouts.app')

@section('title', 'Integer Base Converter - IT Management System')
@section('page-title', 'Integer Base Converter')
@section('page-subtitle', 'Convert a number between different bases (decimal, hexadecimal, binary, octal, base64, ..)')

@section('content')
{{-- Konten HTML tidak berubah, jadi saya singkat --}}
<div class="row justify-content-center">
    <div class="col-lg-8 col-md-10">
        <div class="card animate-fade-in shadow-lg border-0" style="animation-delay: 0.1s;">
            <div class="card-body p-4 p-md-5">
                <!-- Input Section -->
                <div class="row g-3 mb-4">
                    <div class="col-md-6">
                        <label for="input-number" class="form-label fw-medium">Input number</label>
                        <input type="text" class="form-control form-control-lg" id="input-number" value="112">
                    </div>
                    <div class="col-md-6">
                        <label for="input-base" class="form-label fw-medium">Input base</label>
                        <div class="input-group">
                            <button class="btn btn-outline-secondary" type="button" onclick="updateBase('input-base', -1)">-</button>
                            <input type="number" class="form-control form-control-lg text-center" id="input-base" value="10" min="2" max="64">
                            <button class="btn btn-outline-secondary" type="button" onclick="updateBase('input-base', 1)">+</button>
                        </div>
                    </div>
                </div>
                <hr class="my-4">
                <!-- Output Section -->
                <div id="output-container" class="d-flex flex-column gap-3">
                    <!-- Standard bases will be generated by JS -->
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', function() {
    const inputNumberEl = document.getElementById('input-number');
    const inputBaseEl = document.getElementById('input-base');
    const outputContainer = document.getElementById('output-container');

    const standardBases = [
        { name: 'Binary', base: 2 },
        { name: 'Octal', base: 8 },
        { name: 'Decimal', base: 10 },
        { name: 'Hexadecimal', base: 16 },
        { name: 'Base64', base: 64 }
    ];

    // [FIX] Helper function to robustly convert a string from any base to a BigInt
    const baseToBigInt = (str, base) => {
        const digits = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ+/';
        let result = 0n;
        const baseBigInt = BigInt(base);
        for (let i = 0; i < str.length; i++) {
            const digit = str[i];
            const value = digits.indexOf(digit);
            if (value === -1 || value >= base) {
                throw new Error('Invalid character for the given base');
            }
            result = result * baseBigInt + BigInt(value);
        }
        return result;
    };

    // Function to create an output row
    const createOutputRow = (id, label, value = '') => {
        const row = document.createElement('div');
        row.className = 'input-group input-group-lg';
        row.innerHTML = `
            <span class="input-group-text" style="width: 180px;">${label}</span>
            <input type="text" class="form-control" id="${id}" value="${value}" readonly>
            <button class="btn btn-outline-secondary copy-btn" type="button" title="Copy">
                <i class="fas fa-copy"></i>
            </button>
        `;
        return row;
    };

    // Function to create the custom output row
    const createCustomRow = () => {
        const row = document.createElement('div');
        row.className = 'input-group input-group-lg';
        row.innerHTML = `
            <span class="input-group-text" style="width: 100px;">Custom:</span>
            <button class="btn btn-outline-secondary" type="button" onclick="updateBase('custom-base', -1)">-</button>
            <input type="number" class="form-control text-center" id="custom-base" value="36" min="2" max="64" style="max-width: 100px;">
            <button class="btn btn-outline-secondary" type="button" onclick="updateBase('custom-base', 1)">+</button>
            <input type="text" class="form-control" id="custom-output" readonly>
            <button class="btn btn-outline-secondary copy-btn" type="button" title="Copy">
                <i class="fas fa-copy"></i>
            </button>
        `;
        return row;
    };

    // Main conversion logic
    const convert = () => {
        const numberStr = inputNumberEl.value.trim().toLowerCase(); // Convert to lowercase for consistency
        const fromBase = parseInt(inputBaseEl.value, 10);

        if (!numberStr || isNaN(fromBase) || fromBase < 2 || fromBase > 64) {
            clearOutputs();
            return;
        }

        let decimalValue;
        try {
            if (fromBase === 64) {
                // Special handling for Base64 decoding
                const decoded = atob(numberStr);
                decimalValue = BigInt('0x' + Array.from(decoded).map(char => char.charCodeAt(0).toString(16).padStart(2, '0')).join(''));
            } else {
                // [FIX] Use the new robust helper function
                decimalValue = baseToBigInt(numberStr, fromBase);
            }
        } catch (e) {
            console.error(e);
            clearOutputs('Invalid Input');
            return;
        }

        // Now, convert the decimal value to all target bases
        standardBases.forEach(item => {
            const outputEl = document.getElementById(`output-${item.base}`);
            if (outputEl) {
                try {
                    if (item.base === 64) {
                        // Special handling for Base64 encoding
                        if (decimalValue < 0) throw new Error("Base64 requires non-negative numbers");
                        let hex = decimalValue.toString(16);
                        if (hex.length % 2) { hex = '0' + hex; }
                        const bytes = hex.match(/.{1,2}/g).map(byte => parseInt(byte, 16));
                        outputEl.value = btoa(String.fromCharCode.apply(null, bytes));
                    } else {
                        outputEl.value = decimalValue.toString(item.base).toUpperCase();
                    }
                } catch (e) {
                    outputEl.value = 'Error';
                }
            }
        });

        // Handle custom base
        const customBase = parseInt(document.getElementById('custom-base').value, 10);
        const customOutputEl = document.getElementById('custom-output');
        if (customOutputEl && !isNaN(customBase) && customBase >= 2 && customBase <= 64) {
            try {
                if (customBase === 64) {
                    if (decimalValue < 0) throw new Error("Base64 requires non-negative numbers");
                    let hex = decimalValue.toString(16);
                    if (hex.length % 2) { hex = '0' + hex; }
                    const bytes = hex.match(/.{1,2}/g).map(byte => parseInt(byte, 16));
                    customOutputEl.value = btoa(String.fromCharCode.apply(null, bytes));
                } else {
                    customOutputEl.value = decimalValue.toString(customBase).toUpperCase();
                }
            } catch (e) {
                customOutputEl.value = 'Error';
            }
        }
    };

    const clearOutputs = (message = '') => {
        document.querySelectorAll('#output-container input[type="text"]').forEach(input => {
            input.value = message;
        });
    };

    // Initialize UI
    const init = () => {
        outputContainer.innerHTML = ''; // Clear previous
        standardBases.forEach(item => {
            outputContainer.appendChild(createOutputRow(`output-${item.base}`, `${item.name} (${item.base})`));
        });
        outputContainer.appendChild(createCustomRow());

        // Add event listeners
        inputNumberEl.addEventListener('input', convert);
        inputBaseEl.addEventListener('input', convert);
        document.getElementById('custom-base').addEventListener('input', convert);

        // Add copy functionality
        outputContainer.addEventListener('click', function(e) {
            const copyBtn = e.target.closest('.copy-btn');
            if (copyBtn) {
                const inputToCopy = copyBtn.previousElementSibling;
                if(inputToCopy && inputToCopy.value) {
                    navigator.clipboard.writeText(inputToCopy.value).then(() => {
                        const icon = copyBtn.querySelector('i');
                        const originalClass = icon.className;
                        icon.className = 'fas fa-check text-success';
                        setTimeout(() => {
                            icon.className = originalClass;
                        }, 1500);
                    });
                }
            }
        });

        // Initial conversion
        convert();
    };

    init();
});

// Helper function for +/- buttons, made global for onclick
function updateBase(elementId, amount) {
    const el = document.getElementById(elementId);
    if (el) {
        el.stepUp(amount);
        el.dispatchEvent(new Event('input', { bubbles: true })); // Trigger conversion
    }
}
</script>
@endpush
